context:
  version: 0.11.0

package:
  name: bingrep
  version: ${{ version }}

source:
  url: https://github.com/m4b/bingrep/archive/v${{ version }}.tar.gz
  sha256: 3012aef73b3ef5e8b100824af0db2131f81771338fec5f9fe47dc71bf3782506

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - bingrep --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Greps through binaries from various OSs and architectures
  homepage: https://github.com/m4b/bingrep
  repository: https://github.com/m4b/bingrep

extra:
  recipe-maintainers:
    - danielnachun
